### ISSUE TITLE
add comments and examples to slots

### ISSUE THREAD

**Issue by cpauvert** [FAIR-MI/miiid-schema#7]
1. to help during the modelling
2. to provide more documentation when exporting to DataHarmonizer

For instance, in the AMBR schema in DataHarmonizer:

```yaml
 sample collection project name:
    name: sample collection project name
    title: sample collection project name
    description: The name of the project/initiative/program for which the sample was
      collected.
    comments: Provide the name of the project and/or the project ID here. If the information
      is unknown or cannot be provided, leave blank or provide a null value.
    examples:
    - value: Children's Hospital biofilm study (A3-701-01)
    slot_uri: GENEPIO:0100429
    range: WhitespaceMinimizedString
    recommended: true

```
will appear as follow in the DH help

![image](https://github.com/FAIR-MI/miiid-schema/assets/12406679/7c0f713d-e8af-4031-8466-f1168433a7ba)
